env:
  global:
    - PACKAGE_VERSION="5.0.2"
    - PACKAGE_ICON="logo.png"
    - PACKAGE_PROJECT="https://nlib.enbiso.com"
    - PACKAGE_REPO="https://github.com/enbiso/Enbiso.NLib"
    - PACKAGE_COPYRIGHT="Copyright 2021 (c) enbiso. All rights reserved."
language: csharp
mono: none
dotnet: 5.0.101
script:
  - dotnet build -c release -o ./bin
after_success:
  - rm ./bin/*.0.0.1-local.nupkg;
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
    for nupkg in ./bin/*.nupkg; do
    dotnet nuget push $nupkg -s $NUGET_REGISTRY -k $NUGET_API_KEY;
    done
    fi
