name: Nugets CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test: 
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Test
      run: dotnet test --verbosity normal        

  build:
    name: Build & Publish    
    #needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Build Release
      run: dotnet build -c release -o ./bin
      env:
        PACKAGE_VERSION: 5.0.${{ env.GITHUB_RUN_NUMBER }}
        PACKAGE_PROJECT: https://nlib.enbiso.com
        PACKAGE_REPO: https://github.com/enbiso/Enbiso.NLib
        PACKAGE_COPYRIGHT: Copyright 2021 (c) enbiso. All rights reserved.

    - name: Remove local nupkg
      run: rm ./bin/*.0.0.1-local.nupkg

    - name: Publish
      run:  for nupkg in ./bin/*.nupkg; do
              dotnet nuget push $nupkg -s $NUGET_REGISTRY -k $NUGET_API_KEY;
            done   
      env:
        NUGET_REGISTRY: https://packages.nuget.org
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

